name: Pull Request

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: 'true'
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
      - name: Format
        run: pnpm biome
      - name: Package
        run: pnpm package
      - name: Upload Artifacts (Mac)
        uses: actions/upload-artifact@v4
        with:
          name: cmdt-macos
          path: cli/bin/cmdt-macos
      - name: Upload Artifacts (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: cmdt-linux
          path: cli/bin/cmdt-linux
      - name: Upload Artifacts (Win)
        uses: actions/upload-artifact@v4
        with:
          name: cmdt-win
          path: cli/bin/cmdt-win.exe
