name: Pull Request

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: 'true'
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
      - name: Format
        run: pnpm format